sudo: required
services:
  - docker
language: java
jdk: oraclejdk11
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
addons:
  ssh_known_hosts: 81.177.165.24
after_success:
  - export NAME=sylvieshare/kfserv
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
    fi`
  - echo "$D_PASS" | sudo docker login --username "$D_USER" --password-stdin
  - sudo docker build -t $NAME:$COMMIT .
  - sudo docker tag $NAME:$COMMIT $NAME:$TAG
  - sudo docker push $NAME:$TAGs
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh root@81.177.165.24 'bash kfserv_rebuild.sh'
  on:
    branch: master