sudo:
  required

services:
  - docker

language: java
jdk: oraclejdk11

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}


after_success:
  #Оф костыль для работы докера на трависе
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  #-----
  - export NAME=sylvieshare/kfserv
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - echo "$DOCKER_PASSWORD" | sudo docker login --username "$D_NAME" --password-stdin
  - docker build -t $NAME:$COMMIT .
  - docker tag $NAME:$COMMIT $NAME:$TAG
  - docker push $NAME:$TAG