sudo:
  required

services:
  - docker

language: java
jdk: oraclejdk11

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - export NAME=keyforgebah
  - export TAG=`if [ "$TRAVILS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVILS_BRANCH; fi`
  - echo "$DOCKER_PASSWORD" | docker login -u "$D_NAME" --password-stdin
  - docker build -t $NAME:$COMMIT .
  - docker tag $NAME:$COMMIT $NAME:$TAG
  - docker push $NAME