sudo:
  required

services:
  - docker

language: java
jdk: oraclejdk11

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - export NAME=sylvieshare/kfserv
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - echo "$DOCKER_PASSWORD" | sudo docker login --username "$D_NAME" --password-stdin
  - sudo docker build -t $NAME:$COMMIT .
  - sudo docker tag $NAME:$COMMIT $NAME:$TAG
  - sudo docker push $NAME:$TAG